apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  # שם ה-ServiceMonitor
  name: {{ include "my-app-chart.fullname" . }}
  # חשוב: ה-Labels האלה אומרים ל-Prometheus Operator למצוא את ה-SM הזה
  labels:
    # ה-Label הזה מוגדר ב-kube-prometheus-stack כברירת מחדל.
    # הוא אומר ל-Operator "תיקח אותי!"
    release: prometheus-stack
    {{- include "my-app-chart.labels" . | nindent 4 }}
spec:
  selector:
    # זה הלב: ה-ServiceMonitor הזה ימצא
    # את ה-Service של האפליקציה שלך לפי ה-Labels האלה
    matchLabels:
      {{- include "my-app-chart.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http # שם הפורט כפי שהוא מוגדר ב-Service שלך
    path: /metrics # הנתיב שבו האפליקציה חושפת מטריקות
    interval: 15s # כל כמה זמן לגרד מטריקות